apiVersion: v1
kind: Service
metadata:
  name: bringo-frontend
  labels:
    app: bringo-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bringo-frontend
