apiVersion: v1
kind: Service
metadata:
  name: bringo-multimodal-api
  labels:
    app: bringo-multimodal-api

spec:
  type: LoadBalancer
  loadBalancerIP: "34.78.177.35"
  selector:
    app: bringo-multimodal-api
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
